name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "039c9b8062968e61eb0b305c1dc32785505ad5b7975d53c59466012352765837"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
