name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01b25dcca48cde81d580a1dc4c8da5cbcc41d80028c2d7ddb469d29e7800b1e6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
