name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0678118224c7f7ed180da470c22d88c8e0f89b8fc5a0f75c896c7a6090eedd4"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
