name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2f71e3bc613126173f33ad1e146d1fb25a44daba46b21df45c382e3f96b543"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
