name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6989f0c874047b3b12d739ff6f7e5f56182b6b2f77a51b29b3cabb24ddf5386"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
