name = "Ruine Des Civilisations"
author = "Anhgelus Morhtuuzh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b220e17622f4325cfbb6507f93978b8826e9a2bc5728b2999941852adee9aa"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
